
# {rain, boots} = require "rain-boots"
convert = require "convert-boots"

events = require "events"

coffee = require "coffee-script"

exports.rain = new events.EventEmitter()

transform = (code) ->
  js_code = coffee.compile code, bare: yes
  "// Generated By CoffeeScript " +
  coffee.VERSION + "in Rain-boots" + js_code

add_options = (options) ->
  options.transform = transform
  options.filter = "coffee"
  options.extname = "js"

exports.rain.on "watch", (options) ->
  add_options options
  convert.boots.watch options
  convert.rain.on "converted", (file_path) ->
    exports.rain.emit "converted", file_path

exports.rain.on "convert", (options) ->
  add_options options
  convert.boots.convert options
  convert.rain.on "converted", (file_path) ->
    exports.rain.emit "converted", file_path